### ISSUE TITLE
Transient attribute is assigned to model when it refers another factory

### ISSUE THREAD

**Issue by ypresto** [thoughtbot/factory_bot#1024]
When there is `user` factory, below code will raise error:

```rb
FactoryGirl.define do
  factory :group do
    transient do
      user_count 0 # passes
      user # Seems trying to assign user attribute to group instance and fails.
    end

    # Use "user" to create some attribute or from after(:save), etc.
  end
end
```

```
    NoMethodError:
       undefined method `user=' for #<Group:...>
     # /usr/local/bundle/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:16:in `public_send'
     # /usr/local/bundle/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:16:in `block (2 levels) in object'
     # /usr/local/bundle/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:15:in `each'
     # /usr/local/bundle/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:15:in `block in object'
     # /usr/local/bundle/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:14:in `tap'
     # /usr/local/bundle/gems/factory_girl-4.8.0/lib/factory_girl/attribute_assigner.rb:14:in `object'
     # /usr/local/bundle/gems/factory_girl-4.8.0/lib/factory_girl/evaluation.rb:12:in `object'
     # /usr/local/bundle/gems/factory_girl-4.8.0/lib/factory_girl/strategy/create.rb:9:in `result'
     # /usr/local/bundle/gems/factory_girl-4.8.0/lib/factory_girl/factory.rb:42:in `run'
     # /usr/local/bundle/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:29:in `block in run'
     # /usr/local/bundle/gems/factory_girl-4.8.0/lib/factory_girl/factory_runner.rb:28:in `run'
     # /usr/local/bundle/gems/factory_girl-4.8.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
```

**Comment by gnclmorais** [comment]
@ypresto, can you provide more code for your issue, please? For example, the model for `Group` and `User`?

**Comment by composerinteralia** [comment]
I am going to close this issue now since #1290 has a clear description of the issue and most of the discussion has happened over there.
