### ISSUE TITLE
`FactoryBot.reload` error when there is code which modifies factories required by external gems

### ISSUE THREAD

**Issue by mdesantis** [thoughtbot/factory_bot#1113]
I have some factories required by an external gem, `spree_core`. in `spec/factories.rb` I have the `require` of those factories. in `spec/factories.rb` I have a factory which modifies one of them using `FactoryBot.modify`.

Executing`FactoryBot.reload` raises an error, complaining about external factory not defined:

```
> rails r 'FactoryBot.reload'
/home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/factory_bot-4.8.2/lib/factory_bot/registry.rb:24:in `find': Factory not registered: product (ArgumentError)
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/factory_bot-4.8.2/lib/factory_bot/decorator.rb:10:in `method_missing'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/factory_bot-4.8.2/lib/factory_bot.rb:100:in `factory_by_name'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/factory_bot-4.8.2/lib/factory_bot/syntax/default.rb:63:in `factory'
	from /home/maurizio/Sviluppo/app/spec/factories.rb:15:in `block in <top (required)>'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/factory_bot-4.8.2/lib/factory_bot/syntax/default.rb:69:in `instance_eval'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/factory_bot-4.8.2/lib/factory_bot/syntax/default.rb:69:in `run'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/factory_bot-4.8.2/lib/factory_bot/syntax/default.rb:11:in `modify'
	from /home/maurizio/Sviluppo/app/spec/factories.rb:14:in `<top (required)>'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/factory_bot-4.8.2/lib/factory_bot/find_definitions.rb:16:in `block in find_definitions'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/factory_bot-4.8.2/lib/factory_bot/find_definitions.rb:15:in `each'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/factory_bot-4.8.2/lib/factory_bot/find_definitions.rb:15:in `find_definitions'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/factory_bot-4.8.2/lib/factory_bot/reload.rb:6:in `reload'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `<top (required)>'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `eval'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/runner.rb:62:in `<top (required)>'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:90:in `runner'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/maurizio/.asdf/installs/ruby/2.3.6/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
```

 This is especially annoying in conjunction with Spring, since Spring uses `FactoryBot.reload`.

This is my `spec/factories.rb`:

```ruby
require 'spree/testing_support/factories'

FactoryBot.modify do
  factory :product do
    # App specific code
  end
end
```

As a workaround, I'm currently using this, replacing the `require 'spree/testing_support/factories'`:

```ruby
spree_factories_gem_name = 'spree_core'
spree_factories_gem_path = Gem.loaded_specs[spree_factories_gem_name].full_gem_path
spree_factories_path     = File.join spree_factories_gem_path, 'lib/spree/testing_support/factories.rb'

load spree_factories_path
```

**Comment by composerinteralia** [comment]
Instead of requiring or loading the file directly, I think we want to add the spree definitions to `FactoryBot.definition_file_paths` and let FactoryBot handle loading and reloading them all. I think we would have to make that change in spree with something like https://github.com/thoughtbot/factory_bot_rails/issues/180.

**Comment by composerinteralia** [comment]
I'm going to close this issue, since we now have an official way to add definition files, documented here: https://github.com/thoughtbot/factory_bot_rails#automatic-factory-definition-loading. I will try to get factory_bot and factory_bot_rails 5 out soon.
