### ISSUE TITLE
[JRuby, PG-10] currval of sequence "companies_id_seq" is not yet defined in this session

### ISSUE THREAD

**Issue by prashantvithani** [thoughtbot/factory_bot#1170]
Ruby Version:
```bash
jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit Server VM 10.0.2+13 on 10.0.2+13 [darwin-x86_64]
```
Java Version:
```bash
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```
Postgresql Version: `(PostgreSQL) 10.4`
OS: `MacOS 10.13`

Sample:
``` ruby
FactoryBot.define do
  sequence(:id) { |n| n + 1 }
  sequence(:name) { |n| "#{Faker::Company.name}" + n.to_s }

  factory :company do
    id
    name
    currency "INR"
    timezone "Asia/Kolkata"
    approved true
    country do
      Country.where(name: "INDIA").first ||
      Country.create(name: "INDIA", nicename: "India", iso: "IN")
    end
  end

  factory :user do
    id
    name "Test User"
    email { Faker::Internet.email }
    password "password"
    confirmed_at Time.now
    company { create(:company) }
  end
end
```

Above is the sample factory that I'm using in one of my specs, where I'm creating a user object with `create(:user)`. The user factory eventually calls `create(:company)` as seen in the above sample. It's the line that causing below error.

```
ActiveRecord::StatementInvalid:
       ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR: currval of sequence "companies_id_seq" is not yet defined in this session: SELECT currval('public.companies_id_seq') /*hostname:Prashants-MacBook-Pro.local,line:/spec/factories/base_facebook.rb:641:in `block in (root)'*/
     # arjdbc/jdbc/RubyJdbcConnection.java:1091:in `execute_query'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/bundler/gems/activerecord-jdbc-adapter-c5e1abdaaf51/lib/arjdbc/abstract/database_statements.rb:26:in `block in exec_query'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block in log'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/bundler/gems/activerecord-jdbc-adapter-c5e1abdaaf51/lib/arjdbc/abstract/database_statements.rb:26:in `exec_query'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/bundler/gems/activerecord-jdbc-adapter-c5e1abdaaf51/lib/arjdbc/postgresql/adapter.rb:702:in `exec_query'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/marginalia-1.5.0/lib/marginalia.rb:68:in `exec_query_with_marginalia'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/bundler/gems/activerecord-jdbc-adapter-c5e1abdaaf51/lib/arjdbc/postgresql/adapter.rb:381:in `last_insert_id_result'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/bundler/gems/activerecord-jdbc-adapter-c5e1abdaaf51/lib/arjdbc/postgresql/adapter.rb:335:in `exec_insert'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:149:in `insert'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `insert'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/bundler/gems/activerecord-jdbc-adapter-c5e1abdaaf51/lib/arjdbc/abstract/database_statements.rb:48:in `insert'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:157:in `block in method_missing'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block in with'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:136:in `with'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:156:in `method_missing'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/persistence.rb:187:in `_insert_record'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/persistence.rb:733:in `_create_record'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/counter_cache.rb:184:in `_create_record'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/locking/optimistic.rb:70:in `_create_record'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/attribute_methods/dirty.rb:137:in `_create_record'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/callbacks.rb:346:in `block in _create_record'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:816:in `_run_create_callbacks'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/callbacks.rb:346:in `_create_record'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/timestamp.rb:102:in `_create_record'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/persistence.rb:704:in `create_or_update'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/callbacks.rb:342:in `block in create_or_update'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/callbacks.rb:342:in `create_or_update'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/persistence.rb:308:in `save!'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/validations.rb:52:in `save!'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:315:in `block in save!'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:157:in `block in method_missing'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block in with'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:136:in `with'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:156:in `method_missing'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:212:in `transaction'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:315:in `save!'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activerecord-5.2.1/lib/active_record/suppressor.rb:48:in `save!'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/factory_bot-4.10.0/lib/factory_bot/configuration.rb:18:in `block in initialize'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/factory_bot-4.10.0/lib/factory_bot/evaluation.rb:18:in `create'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/factory_bot-4.10.0/lib/factory_bot/strategy/create.rb:12:in `block in result'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/factory_bot-4.10.0/lib/factory_bot/strategy/create.rb:9:in `result'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/factory_bot-4.10.0/lib/factory_bot/factory.rb:43:in `run'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/factory_bot-4.10.0/lib/factory_bot/factory_runner.rb:29:in `block in run'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/activesupport-5.2.1/lib/active_support/notifications.rb:170:in `instrument'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/factory_bot-4.10.0/lib/factory_bot/factory_runner.rb:28:in `run'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/factory_bot-4.10.0/lib/factory_bot/strategy_syntax_method_registrar.rb:20:in `block in create'
     # /Users/prvithani/.rvm/gems/jruby-9.2.0.0/gems/factory_bot-4.10.0/lib/factory_bot/evaluator.rb:44:in `method_missing'
     # ./spec/factories/base_facebook.rb:641:in `block in (root)'
```
Then, I added a `puts` statement in `database_statements.rb` of `ActiveRecord` to see the query being made to DB. The query was
```
SELECT  1 AS one FROM "companies" WHERE "companies"."name" = ? AND "companies"."agency_id" IS NULL LIMIT ? /*hostname:Prashants-MacBook-Pro.local,line:/spec/factories/base_facebook.rb:641:in `block in (root)'*/
----------------------------------------
SELECT currval('public.companies_id_seq') /*hostname:Prashants-MacBook-Pro.local,line:/spec/factories/base_facebook.rb:641:in `block in (root)'*/
----------------------------------------
```
It's clear that the **second** `SELECT` statement in above snippet is throwing the error. **Interesting part here is that that error causing statement is not seen when I downgrade Postgres version to `9.6` from `10`**

**Comment by prashantvithani** [comment]
After some digging, I've identified that this is the issue with JRuby's [activerecord-jdbc-adapter](https://github.com/jruby/activerecord-jdbc-adapter). You have to pass `insert_returning: true` in if you're using PG-10 (It's kind of broken for PG-10, It works fine in version <= 9.x), in order to return ID of the saved record such that it doesn't fallback to `SELECT currval('public.companies_id_seq')` to get the last saved ID.
