### ISSUE TITLE
FactoryBot fails to find the class when loading definition

### ISSUE THREAD

**Issue by dcatt-haiku** [thoughtbot/factory_bot#1269]
I discovered when I updated to 5.0.1 from 4.10.0 that FactoryBot fails to find the class when loading the definition...
```ruby
# gem 'factory_bot', '4.10.0'
gem 'factory_bot', '5.0.1'

require 'factory_bot'

Foobar = Struct.new(:foo, :bar)

FactoryBot.define do
  
  factory :foobar do
    foo 'foo'
    bar 'bar'
  end
  
  initialize_with { new }
  skip_create
end

# load '~/Desktop/factory_bot_with_struct.rb'
```
Which results in the following...
```
12: from /.../.asdf/installs/ruby/2.5.0/bin/irb:11:in `<main>'
11: from (irb):1
10: from (irb):1:in `load'
9: from /.../Desktop/factory_bot_with_struct.rb:8:in `<top (required)>'
8: from /.../.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/factory_bot-5.0.1/lib/factory_bot/syntax/default.rb:7:in `define'
7: from /.../.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/factory_bot-5.0.1/lib/factory_bot/syntax/default.rb:49:in `run'
6: from /.../.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/factory_bot-5.0.1/lib/factory_bot/syntax/default.rb:49:in `instance_eval'
5: from /.../Desktop/factory_bot_with_struct.rb:10:in `block in <top (required)>'
4: from /.../.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/factory_bot-5.0.1/lib/factory_bot/syntax/default.rb:18:in `factory'
3: from /.../.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/factory_bot-5.0.1/lib/factory_bot/syntax/default.rb:18:in `instance_eval'
2: from /.../Desktop/factory_bot_with_struct.rb:11:in `block (2 levels) in <top (required)>'
1: from /.../.asdf/installs/ruby/2.5.0/lib/ruby/gems/2.5.0/gems/factory_bot-5.0.1/lib/factory_bot/definition_proxy.rb:97:in `method_missing'
NoMethodError (undefined method 'foo' in 'foobar' factory)
```

**Comment by mikegee** [comment]
I don't really understand the error, but I notice that you're using static attributes which [were deprecated in 4.11 and removed in 5](https://thoughtbot.com/blog/deprecating-static-attributes-in-factory_bot-4-11). Try running that example on 4.11 to see if you get a helpful warning.

**Comment by composerinteralia** [comment]
Yup, that is what the `NoMethodError (undefined method 'foo' in 'foobar' factory)` error is about. The advice to update to 4.11 first is correct. Thanks @mikegee!

See https://thoughtbot.com/blog/deprecating-static-attributes-in-factory_bot-4-11 for details on the deprecation.

**Comment by dcatt-haiku** [comment]
I'll play around and see if I can come to terms with the issue.

**Comment by dcatt-haiku** [comment]
Based on what was shared here and after I wrapped my head around the mentioned change... closing issue!
