### ISSUE TITLE
factory_bot 5.1.0 does not play nicely with jruby (lambdas don't splat the way they should)

### ISSUE THREAD

**Issue by dsimmsatsquare** [thoughtbot/factory_bot#1331]
### Steps to reproduce
```
~/Development/scrach master * bundle console
jruby-9.1.17.0 :001 > require 'factory_bot'
ArgumentError: wrong number of arguments (1 for 2)
	from /Users/dsimms/.rvm/gems/jruby-9.1.17.0/gems/factory_bot-5.1.0/lib/factory_bot/internal.rb:89:in `register_strategy'
	from org/jruby/RubyHash.java:1350:in `each'
	from /Users/dsimms/.rvm/gems/jruby-9.1.17.0/gems/factory_bot-5.1.0/lib/factory_bot/internal.rb:89:in `register_default_strategies'
	from /Users/dsimms/.rvm/gems/jruby-9.1.17.0/gems/factory_bot-5.1.0/lib/factory_bot.rb:124:in `<main>'
	from org/jruby/RubyKernel.java:956:in `require'
	from (irb):1:in `<eval>'
	from org/jruby/RubyKernel.java:995:in `eval'
	from (irb):1:in `evaluate'
	from org/jruby/RubyKernel.java:1316:in `loop'
	from org/jruby/RubyKernel.java:1138:in `catch'
	from org/jruby/RubyKernel.java:1138:in `catch'
	from /Users/dsimms/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.0.2/lib/bundler/cli/console.rb:19:in `run'
	from /Users/dsimms/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.0.2/lib/bundler/cli.rb:496:in `console'
	from /Users/dsimms/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/dsimms/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/dsimms/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	from /Users/dsimms/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
	from /Users/dsimms/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	from /Users/dsimms/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `block in start'
	from /Users/dsimms/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.0.2/exe/bundle:30:in `(root)'
	from /Users/dsimms/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `<main>'
	from org/jruby/RubyKernel.java:974:in `load'
	from /Users/dsimms/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.0.2/exe/bundle:22:in `<eval>'
	from org/jruby/RubyKernel.java:995:in `eval'
	from /Users/dsimms/.rvm/gems/jruby-9.1.17.0/bin/bundle:1:in `<main>'
jruby-9.1.17.0 :002 >
~/Development/scrach master * rvm list
=> jruby-9.1.17.0 [ x86_64 ]
   ruby-2.4.4 [ x86_64 ]
 * ruby-2.4.5 [ x86_64 ]
   ruby-2.5.3 [ x86_64 ]
   ruby-2.5.5 [ x86_64 ]
   ruby-2.6.2 [ x86_64 ]
   ruby-2.6.3 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

### Expected behavior

factory_bot does't even load

### Actual behavior

should load

### System configuration
**factory_bot version**:  5.1.0
**rails version**:  none
**ruby version**: jruby-9.1.17.0

**Comment by composerinteralia** [comment]
Based on the error message I think this was caused by f82e40c8c50c538c0fba0362c0f6b7f6f96f9a3c. Is there a known bug in jruby that would prevent us from running https://github.com/thoughtbot/factory_bot/blob/ad7a58d304243bc2aa5f505be3d75a2effe18195/lib/factory_bot/internal.rb#L89

If so, we could work around that by getting rid of the constant entirely and going back to

```rb
    register_strategy(:build,          FactoryBot::Strategy::Build)
    register_strategy(:create,         FactoryBot::Strategy::Create)
    register_strategy(:attributes_for, FactoryBot::Strategy::AttributesFor)
    register_strategy(:build_stubbed,  FactoryBot::Strategy::Stub)
    register_strategy(:null,           FactoryBot::Strategy::Null)
```

We may also need to do that with `register_default_callbacks`.

I would be glad to keep factory_bot working with jruby (even though we did stop testing against it in 9f1b32e07100d9a7da5439532b14cb7c349a2563 because the tests had been failing for quite some time), but it would be good for somebody who uses jruby to take the lead on that. Is this something you would be interested in working on?

**Comment by mvz** [comment]
I filed a new bug with JRuby about this: https://github.com/jruby/jruby/issues/5896

**Comment by mvz** [comment]
@composerinteralia I made a pull request for this in #1335.

**Comment by dsimmsatsquare** [comment]
Thanks y'all!
